### ISSUE TITLE
dbus: handle devices that disappeare

### ISSUE THREAD

**Issue by mpvader** [mpvader/venus-signalk#12]
When a Device stops sending data, or otherwise can’t be reached anymore (powered down, unplugged, etc), it’s D-Bus service disconnects.

The point in the code where that happens is here:
https://github.com/mpvader/venus-signalk/blob/master/dbus-listener.js

Do we need to do anything in SignalK when that happens? What?

**Comment by mpvader** [comment]
Also @sbender9 , any thoughts?

**Comment by tkurki** [comment]
Outgoing deltas stop, the values in the full tree remain, but with timestamp that indicates staleness, last known values. This is how things stand from spec perspective, so no action required.

SK Node server has code for removing timed out ais targets, but not timed out data items.
